### ISSUE TITLE
Firm files not recognized in em9/payloads folder

### ISSUE THREAD

**Issue by SSQ123** [eiiiiix/EixMode9#2]
**What version of EixMode9 are you using?**
1.4.4.8.1-E
**How are you launching it? (If applicable)**
Luma3DS
**What version is your SysNand on (Emu/RedNand if applicable), and is it Retail or Dev?**
11.6 sys retail
**Now, what exactly IS the issue?**
Firm files don't show up in home menu
**Explain in great detail all neccessary steps to reproduce.**
Copy firm files to /em9/payloads
press home or power
look through menu
Any other details.
Lot's of issues in this program, but I need to find them as a tester! XD

**Comment by eiiiiix** [comment]
that is not a bug
put them in gm9/payloads

**Comment by Moire9** [comment]
@eiiiiix I have moved everything to /em9 in my fork. I think it's better that way.

**Comment by eiiiiix** [comment]
it may be beter but what if you also use gm9?

**Comment by eiiiiix** [comment]
if you use both then you need dupe files
my payloads folder is borderline 100mb
since i use both gm9 and em9 moving everything to 0:em9/ would mean i need to use an extra 100mb and copy new payloads in twice
the only things that would be good to move is /out and /scripts for organisation and compatability
im not able to actively work on em9 until ~late february so if you want to take over for a bit thats fine
but please make sure to think before you act

**Comment by Moire9** [comment]
You can seperate them completely.
I also cleaned up the readme, can you merge my fork?

**Comment by Moire9** [comment]
Idea: Search for stuff in /em9, if you can't find it looks in /gm9
I don't know how to do that, though.

**Comment by SSQ123** [comment]
At least allow you to customize the em9 folder

**Comment by Moire9** [comment]
Yeah, in the fork i made it checked for files in /em9, if it didn't find them it used /gm9

**Comment by Moire9** [comment]
But that was merged, so it should be in master
also, don't use my fork, it's broken rn
